services:
  node:
    image: node:latest
    volumes:
      - ./app:/app
      - '/app/node_modules'
    working_dir: /app
    ports:
      - "3000:3000"
    command: "npm run docker"
    environment:
      - CHOKIDAR_USEPOLLING=true
